name: Deploy Jekyll site to gh-pages

on:
  push:
    branches:
      - v0  # Uruchamiaj workflow na push w gałęzi v0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0  # Wersja Ruby zgodna z Jekyll

      - name: Install dependencies
        run: |
          bundle install

      - name: Build the site
        run: |
          bundle exec jekyll build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_site